'use client';
import {useEffect,useRef,useState} from 'react';
import {Anchor,Check,Headphones,Play,RotateCcw,Square,Volume2} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import {animals,makeExpedition,ROUND_COUNT} from '@/lib/expedition.mjs';
import {OceanAudio} from '@/lib/ocean-audio.mjs';
export default function Home(){
 const [screen,setScreen]=useState('intro'),[index,setIndex]=useState(0),[ready,setReady]=useState(false),[loaded,setLoaded]=useState(0),[error,setError]=useState(''),[playing,setPlaying]=useState(false),[heard,setHeard]=useState(false),[answer,setAnswer]=useState<string|null>(null),[score,setScore]=useState(0);
 const engine=useRef<OceanAudio|null>(null),plans=useRef<any[]>([]),busy=useRef(false),alive=useRef(true);const plan=plans.current[index],target=animals.find(a=>a.id===plan?.target);const base=()=>new URL('./',window.location.href).pathname;
 function audio(){return engine.current||(engine.current=new OceanAudio());}function stop(){audio().stop();busy.current=false;setPlaying(false);}function speak(text:string){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.9;u.pitch=1.08;window.speechSynthesis.speak(u);}function directions(){speak('Welcome, explorer! Listen to the animal sound, then tap the animal you think made it. The first two are warm ups. Then you will unlock a mystery sound from the ocean!');}
 useEffect(()=>{alive.current=true;const hide=()=>{if(document.hidden){engine.current?.interrupt();busy.current=false;setPlaying(false);}};document.addEventListener('visibilitychange',hide);return()=>{alive.current=false;document.removeEventListener('visibilitychange',hide);engine.current?.interrupt();window.speechSynthesis?.cancel();};},[]);
 function load(){setError('');try{const e=audio();void e.unlock();void e.load(base(),n=>alive.current&&setLoaded(n)).then(()=>{if(alive.current){e.prepare(plans.current);setReady(true);speak('Listen to the sound. Then tap the animal that made it.');}}).catch(()=>alive.current&&setError('Sounds could not load. Tap to try again.'));}catch{setError('Sound is unavailable. Please try Safari or Chrome.');}}
 function start(){plans.current=makeExpedition();setIndex(0);setScore(0);setAnswer(null);setHeard(false);setReady(false);setLoaded(0);setScreen('game');directions();load();}function play(){if(busy.current||!ready)return;window.speechSynthesis?.cancel();setError('');busy.current=true;setPlaying(true);const p=plans.current[index];audio().play(p.layers,p.duration,()=>{busy.current=false;setPlaying(false);setHeard(true);speak(index<2?'Which animal made that sound? Tap the animal!':'Who made that ocean sound? Take your best guess!');},()=>{busy.current=false;setPlaying(false);setError('Oops — the sound stopped. Tap the big sound button to hear it again.');});}function choose(id:string){if(!heard||playing||answer)return;setAnswer(id);if(id===plan.target)setScore(s=>s+1);const chosen=id===plan.target?'You found it!':`Good guess! It was the ${target?.name}.`;speak(chosen+' '+(target?.fact||''));}function next(){stop();if(index===ROUND_COUNT-1){setScreen('done');speak('Mission complete! Great listening. Want to hear what the dolphin and seal sound like too?');return;}setIndex(i=>i+1);setHeard(false);setAnswer(null);setError('');setTimeout(()=>speak(index===1?'Now for the ocean mystery! Listen carefully, then take your best guess.':'Ready for the next sound?'),100);}
 function learn(kind:'dolphin'|'seal'){window.speechSynthesis?.cancel();if(kind==='dolphin'){const a=new Audio(base()+'audio/dolphin.mp3');a.volume=1;a.play();}else{const a=new Audio('https://commons.wikimedia.org/wiki/Special:Redirect/file/Arctocephalus_forsteri_-_sound.ogg');a.volume=1;a.currentTime=4;a.play();setTimeout(()=>a.pause(),5000);}}
 return <main className="expedition"><header><span className="brand"><Anchor/><span>Sound<br className="mobile-break"/> Explorer</span></span></header>
 {screen==='intro'?<section className="console intro"><div className="intro-photo"><img src="./animals/dolphin.webp" alt="A dolphin"/><span className="mission-tag"><Headphones size={18}/> SOUND MISSION</span></div><div className="intro-body"><span className="eyebrow">AHOY, EXPLORER!</span><h1>Who made<br/>that sound?</h1><p className="story">Start with two sounds you may know. Then unlock a mystery sound from the ocean.</p><button className="mix-button big" onClick={directions}><Volume2/> Hear how to play</button><button className="primary big" onClick={start}><Play fill="currentColor"/> Start!</button><span className="small">3 quick sounds · Easy first, then a surprise</span></div></section>:
 screen==='done'?<section className="console done"><span className="medal">🌊</span><span className="eyebrow">MISSION COMPLETE</span><h1>Great listening!</h1><p>You discovered a beluga whale sound. Want to discover the other two?</p><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:12,width:'100%',maxWidth:520}}><button className="mix-button big" onClick={()=>learn('dolphin')}><span style={{fontSize:'3rem'}}>🐬</span><Volume2/> Hear a dolphin</button><button className="mix-button big" onClick={()=>learn('seal')}><span style={{fontSize:'3rem'}}>🦭</span><Volume2/> Hear a seal</button></div><button className="primary big" onClick={start}><RotateCcw/> Play again!</button></section>:
 <><div className="journey"><span>Sound {index+1} of {ROUND_COUNT}</span><div className="steps">{Array.from({length:ROUND_COUNT},(_,i)=><span key={i} className={i<index?'visited':i===index?'current':''}>{i<index?<Check size={18}/>:i+1}</span>)}</div><span className="stars">★ {score}</span></div><section className="console game"><div className="control-panel" style={{width:'100%',maxWidth:760,margin:'0 auto'}}>{!ready?<div className="loading"><Headphones size={36}/><h2>Getting your mystery sounds…</h2><Progress value={(loaded/8)*100}/><p>{loaded} sounds ready</p>{error&&<button className="primary big" onClick={load}>Try again</button>}</div>:<><div style={{textAlign:'center'}}><span className="eyebrow">{index<2?`WARM-UP SOUND ${index+1}`:'OCEAN MYSTERY'}</span><h1>👂 Listen!</h1><h2>{index<2?'Which animal made this sound?':'New sound! Take a guess — who made it?'}</h2></div><button className={'primary big audio-button '+(playing?'is-playing':'')} onClick={()=>playing?stop():play()}>{playing?<Square/>:<Volume2/>}{playing?'Stop':'▶ Hear the sound'}</button>{error&&<p className="error">{error}</p>}{heard&&<><div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:12}}>{plan.choices.map((a:any)=><button key={a.id} onClick={()=>choose(a.id)} disabled={!!answer} style={{padding:10,borderRadius:20,border:answer===a.id?'4px solid currentColor':'2px solid #d8e8ef',background:'white',fontWeight:800}}><span style={{display:'grid',placeItems:'center',aspectRatio:'1/1',fontSize:'clamp(3.5rem,15vw,7rem)'}}>{a.emoji||a.icon}</span><span>{a.name}</span></button>)}</div><button className="mix-button big" onClick={play}><Volume2/> Hear it again</button></>}{answer&&<div className="feedback"><div className="feedback-title"><span>{answer===plan.target?'🌟':'✨'}</span><h2>{answer===plan.target?'You found it!':`Let’s find out — it was the ${target?.name}!`}</h2></div><p className="fact">{target?.fact}</p><button className="primary big" onClick={next}>{index===ROUND_COUNT-1?'Finish!':'Next sound →'}</button></div>}</>}</div></section></>}
 <footer><a href="./credits.html">For grown-ups · Sounds & photo credits</a><span>Made for curious ears.</span></footer></main>;
}
